### ISSUE TITLE
Keplr reports insufficient funds for fee

### ISSUE THREAD

**Issue by greg-szabo** [samepant/cosmoshub-legacy-multisig#4]
Great tool, I hope I can play around with it even more.

I've opened an issue on the Keplr extension source code because the transactions created by the tool are reporting an error from Keplr: "Insufficient available balance for transaction fee". Details are here: https://github.com/chainapsis/keplr-extension/issues/204

**Comment by samepant** [comment]
Thanks for bringing this up, looks like it will get fixed soon, (based on chainapsis's response).

**Comment by Thunnini** [comment]
From Keplr@v0.9.9, the wallet will take into consideration the sender address in the msgs in the tx. I expect it will reduce this problem. However, for fee part, I'm yet not sure how to consider the payer of tx because the increased number of fee system (multi-sig, authz, feegrant...). So, the keplr assume that the fee payer should be the selected account on the keplr. If the account has enough balance to pay fee, it can approve the signature, but, if it has no balance, user can't approve the signature due to the insufficient balance error.
For now, to solve this problem, I recommend to set the `disableBalanceCheck` to true.
```
window.keplr.defaultOptions = {
  disableBalanceCheck: true
}
```

**Comment by greg-szabo** [comment]
@samepant I think this will require a bit of change (or extra feature/option) on the app side too, right?

**Comment by samepant** [comment]
@greg-szabo correct, [just made the change here](https://github.com/samepant/cosmoshub-legacy-multisig/commit/bff22b61cc3f65bd73a92f8f13b2b16d3140b928).

A version with this change is now deployed at https://cosmoshub-legacy-multisig.vercel.app/

**Comment by greg-szabo** [comment]
Tested using the latest Keplr. Works fine! Thanks for the fix.
